### ISSUE TITLE
검색 결과 없음 오류

### ISSUE THREAD

**Issue by min-seon-kim** [Kain7f1/Naver-News-Crawler#38]
안녕하세요. 
현재 해당 search_url 그대로 이용 가능한가요? 혹시 수정된 사항있으면 공유 부탁드립니다:)

main에서 search_keyword를 "축구"와 같은 일반적인 키워드를 사용해도, [검색 결과가 없습니다]라고 next date로 넘어가는 것 같습니다.

감사합니다.

**Comment by Kain7f1** [comment]
코멘트 감사합니다
확인해보겠습니당

**Comment by Kain7f1** [comment]
네이버가 방식을 수정한 것 같군요

[이전처럼 작동되지 않는 원인]

1. 네이버 url의 유니코드 표기방식 변경
  과거 - "축구" 키워드의 유니코드 : .EC.B6.95.EA.B5
  현재 - "축구" 키워드의 유니코드 : %EC%B6%95%EA%B5%

2. 페이징 방식 변경
  과거 - 컨텐츠가 11개 이상이면 10개 단위로 페이징 됨
  현재 - 스크롤 할 때마다 컨텐츠가 추가됨

**Comment by Kain7f1** [comment]
유니코드는 간단히 수정했고 #39 
페이징은 selenium으로 스크롤 쭉 땡겨서 하면 될 것 같습니다
